Forgot Password | Reset Password
AnasKhaled7/PMS-React pull request #2
Opened 2024-03-14 12:32 UTC by Mai-Fouad

2024-03-14 22:05 UTC, Mohamed-Esmat approved these changes
Your code is well-organized and easy to follow! 👍📝 Maintaining clear and concise code structure enhances readability and maintainability. Keep up the good work in writing clean and readable code! 🌟

2024-03-15 12:16 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                      className={`fa-regular text-light fa-eye${
I think we should flip the icons to represent the current state:
eye slash: the password is hidden and you can't see the password (because there's slash over the eyes)
eye: the password is visible
![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/ddfb281a-ad7d-440c-8d55-149155b88e7e)

We can also look at a real example if we forget such as facebook:
![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/36f7d94f-6e67-4aeb-952a-05fb9badcb6b)

2024-03-15 12:18 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +      toast.success("Password has been updated successfully");
This should be "reset" not "updated". Updating feels like we are changing our password, but we actually forgot it so we are resetting not updating.

2024-03-15 12:26 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                        value:
@AnasKhaled7  was doing something that I  really liked in the previous project. He was separating all the validation logic into a separate file, and using it in the application [see his example](https://github.com/AnasKhaled7/FMS-React/blob/main/src/lib/validator.js). 

This approach will make the component more abstract concise and easier to read. 
It will also reduce repetition, since we have,for example, emailValidation logic in one place and re-use it in all other places.  
We  will also have a single source of truth that we can update and the update goes to all components.

I suggest doing the same here as well.

2024-03-15 12:32 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                      onClick={() => showPassHandler("password")}
I think it would be better if we changed this to a button, because we have an onClick here. This will make it accessible for keyboard users as well by using the tap to navigate through them and space or enter to toggle the password.

2024-03-15 12:37 UTC, Ahmed-Abou-Emran commented on src/Context/AuthContext.tsx
> +  const baseURL = "https://upskilling-egypt.com:3003/api/v1";
Consider comparing between this approach for storing constants like URLs and storing them in  a separate file for example "APIs.ts"

2024-03-15 12:52 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                    "Save"
Consider changing this text to something more meaningful and relevant to the context such as: "Reset Password"

2024-03-15 12:53 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/ForgotPass/ForgotPass.tsx
> +                    "Verify"
This could be changed to "Request Rest" or "Request Reset Password".

2024-03-15 12:55 UTC, Ahmed-Abou-Emran commented
The focus state of the submit button is not handled properly or overridden by other styles, this is how it looks when we navigate by the tap key:

![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/83499715-9c07-4cd6-9cfa-e506641566f0)

2024-03-15 13:18 UTC, Ahmed-Abou-Emran requested changes
Great work! I've thoroughly reviewed your code and tested the application – it's functioning smoothly. While everything looks great, I've added a few comments suggesting improvements. I'll eagerly await your completion of these adjustments. Please commit the changes and submit another review request when you're ready.

2024-03-15 19:52 UTC, Mai-Fouad commented on src/AuthModule/components/ForgotPass/ForgotPass.tsx
> +                    "Verify"
Done

2024-03-15 19:52 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                    "Save"
Done

2024-03-15 19:53 UTC, Mai-Fouad commented on src/Context/AuthContext.tsx
> +  const baseURL = "https://upskilling-egypt.com:3003/api/v1";
Done

2024-03-15 19:54 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                        value:
Done

2024-03-15 19:54 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +      toast.success("Password has been updated successfully");
Done

2024-03-15 19:55 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                      className={`fa-regular text-light fa-eye${
Done

2024-03-15 20:24 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                  {isSubmitting ? (
Done

2024-03-15 20:43 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                    <i
Done

2024-03-15 20:43 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                    placeholder="Enter Verification"
Done

2024-03-15 20:49 UTC, Mai-Fouad commented on src/AuthModule/components/ForgotPass/ForgotPass.tsx
> +              <form noValidate onSubmit={handleSubmit(onSubmit)}>
Done

2024-03-16 14:29 UTC, Ahmed-Abou-Emran commented on src/lib/APIs.ts
> +const baseURL = "https://upskilling-egypt.com:3003/api/v1";
I meant to store the baseURL only, but if you are planning on having all the URLs in one file, this is a good option. We can even improve it by storing  all related links in one object, so we don't have to remember the names of the APIs such as the following:
![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/4a4cfb8f-d2db-44bb-b80b-f7966e5dd6da)

The benefit of this is that we write the APIs once, and then forget about it.

2024-03-16 14:33 UTC, Ahmed-Abou-Emran approved these changes

2024-03-16 20:41 UTC, Mai-Fouad commented on src/lib/APIs.ts
> +const baseURL = "https://upskilling-egypt.com:3003/api/v1";
Done

2024-03-16 20:42 UTC, Mai-Fouad commented on src/AuthModule/components/ResetPass/ResetPass.tsx
> +                      {(errors.email as FieldError).message}
Done

2024-03-17 15:25 UTC, merged