registeration & verification
AnasKhaled7/PMS-React pull request #4
Opened 2024-03-15 11:08 UTC by AnasKhaled7

2024-03-16 14:41 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +    let registerFormData = appendToFormData(data);
It is a good practice that if we have variables that we don't change through the application to have them as constants. We change this one and the following ones to const variables.

2024-03-16 14:44 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +                        <i
it would be better if we changed this to a button because we have an `onClick` here. This will make it accessible for keyboard users as well by using the tap to navigate through them and space or enter to toggle the password.

2024-03-16 14:45 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +                        <i
I think we should flip the icons to represent the current state:
eye slash: the password is hidden and you can't see the password (because there's slash over the eyes)
eye: the password is visible
![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/ddfb281a-ad7d-440c-8d55-149155b88e7e)

We can also look at a real example if we forget such as facebook:
![image](https://github.com/AnasKhaled7/PMS-React/assets/64327685/36f7d94f-6e67-4aeb-952a-05fb9badcb6b)

2024-03-16 14:50 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +  const [showPass, setShowPass] = useState(false);
This state is currently responsible for two password inputs, using the toggle button of any of them, will toggle both.
We need one for each of them or to store them in an object state.

We can even abstract the password input with toggle functionality into a separate component and have the state inside of it and when needed we don't have to write the toggle logic multiple times because it will be in the component itself.

2024-03-16 14:53 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +                          required: "Email is required",
We need to get these validations from the validations files after the other branch is merged.

2024-03-16 15:27 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +                          required: "phoneNumber  is required",
We might add a phone validation here.

2024-03-16 15:28 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/Register/Register.tsx
> +                    "Save"
We might change this text to "Register"

2024-03-16 15:31 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/VerifyAccount/VerifyAccount.tsx
> +  const showPassHandler = () => setShowPass(!showPass);
We don't need the toggle button for the OTP. We can remove this handler and the state it manges.

2024-03-16 15:31 UTC, Ahmed-Abou-Emran commented on src/AuthModule/components/VerifyAccount/VerifyAccount.tsx
> +                    "Save"
We can change this to "Verify Account"

2024-03-16 15:32 UTC, Ahmed-Abou-Emran requested changes
Great work! I've thoroughly reviewed your code and tested the application – it's functioning smoothly. While everything looks great, I've added a few comments suggesting improvements. I'll eagerly await your completion of these adjustments. Please commit the changes and submit another review request when you're ready.

2024-03-17 15:34 UTC, Mohamed-Esmat approved these changes
🎉 Great job on implementing the registration and account verification flows! Remember to regularly review and update the code to address any potential security vulnerabilities and improve user experience.

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/Register/Register.tsx
> +                          required: "userName is required",
📝 The user name input lacks feedback to users regarding the expected format. Additionally, the backend requires the user name to contain characters and end with numbers without spaces. Consider providing clear instructions or validation messages to guide users and ensure compliance with backend requirements.

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/Register/Register.tsx
> +                        {...register("userName", {
🛡️ **Strong validation** for the user name is crucial to prevent potential security vulnerabilities, such as injection attacks or malicious input. Consider implementing validation rules that restrict the allowed characters, length, and format of the user name to mitigate risks.

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/Register/Register.tsx
> +                        {...register("confirmPassword", {
🛡️ Ensure that both the password and confirm password fields are validated to match. Implement validation logic to compare the values entered in these fields and provide appropriate feedback to users if they do not match, preventing potential account creation errors and enhancing user experience.

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/Register/Register.tsx
> +                        type={showPass ? "text" : "confirmPassword"}
There is a typo here. It should be `password` instead of `confirmPassword`

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/VerifyAccount/VerifyAccount.tsx
> +              <img src={logo} alt="Logo" />
Consider adding a more descriptive `alt` to improve the `accessibility` and the `SEO`

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/VerifyAccount/VerifyAccount.tsx
> +import style from "../Login/Login.module.css";
Since you needed some styles from the `Login.module.css` it's better practice to add these styles in a more general file.

2024-03-17 15:34 UTC, Mohamed-Esmat commented on src/AuthModule/components/VerifyAccount/VerifyAccount.tsx
> +                {/* links */}
Since you don't need those lines you commented it's better to delete them.

2024-03-19 14:32 UTC, merged