Add projects page
AnasKhaled7/PMS-React pull request #6
Opened 2024-03-24 15:14 UTC by AnasKhaled7

2024-03-26 12:25 UTC, Ahmed-Abou-Emran commented on src/ProjectsModule/components/DeleteModal.tsx
> +      handleClose();
I believe it would give a better user experience if we put the `handleClose()` in the try block,  as putting it in the finally block will close the modal if there's an error. But if there is an error, it would be better if we left the modal open and show a toast message that there is an error, and leave the modal open for the user to try again.

2024-03-26 12:30 UTC, Ahmed-Abou-Emran commented on src/ProjectsModule/Projects.tsx
> +  const [pageNumber, setPageNumber] = useState(1);
if we change the title and the page and then reload the page, everything will be cleared. This gives a bad user experience, since we need to update all the params again.

To fix this issue and give a better user experience, we can use the `useSearchParams` hook from react-router-dom. It will store the params that we set in the URL, and we can refresh the page and get the same values again.

It will also have the benefit of being able to share the link with other people to get exactly what we see, this is good if our website is a public one.

2024-03-26 12:37 UTC, Ahmed-Abou-Emran commented on src/ProjectsModule/Projects.tsx
> +    pageNumber: number,
I suggest taking the parameters as a single object, I prefer that for multiple reasons:
1-  We don't need to remember the order of the params as we can write them as:
```
{pageNumber:15; 
 pageSize:20;
title:"myProject";
}

or

{
title:"myProject";
pageNumber:15; 
 pageSize:20;
}
```
2- It also make the code more readable, as we know exactly what each number reprsent, currently when we call the function it looks something like `getProjects(1,5,"myTitle")`  and we need to see the function definition to see what each value represents.

2024-03-26 12:39 UTC, Ahmed-Abou-Emran commented on src/ProjectsModule/Projects.tsx
> +    pageNumber: number,
We can also add default values for the function for the page number and page size and title, so that we can call `getProjects()` without needing to provide the values for all parameters, since they should be optional not required.

2024-03-26 12:40 UTC, Ahmed-Abou-Emran commented on src/ProjectsModule/Projects.tsx
> +      setError("An error occurred while fetching projects. Please try again.");
We need to provide the error coming from the backend, and the current error should be a fallback for it.

2024-03-26 13:02 UTC, Ahmed-Abou-Emran commented
Currently, if we clear the local storage and sign in, the APIs that need the token will not work unless we refresh the page.
This issue happens because the token is initially null, and when we sign in we don't update the token in the context.

We can fix this issue either by having the token as a state in the context and then updating it when needed, the other option and which I prefer is to access the token from local storage directly in the API call without storing it in the context.

![token issue](https://github.com/AnasKhaled7/PMS-React/assets/64327685/e3aa1b8e-fecd-45bc-b5ba-2062a534a90e)

2024-03-26 14:42 UTC, Ahmed-Abou-Emran requested changes
Overall, you really did a great job and I really appreciate your hard working and attention to details and making a good component structure and reusing your code.
There are just  a few comments that suggest some improvements or fix some issues. You can look at them and request another review once you've finished. 

If you have any question regarding any of the comments, you can ask me at any time.

2024-03-27 00:18 UTC, AnasKhaled7 commented
The last issue of the context that you provided, I tried multiple times, but the issue is not happening with me. I do not know why, but I made some changes in the context, but I do not know if it will fix this issue or not.

2024-03-27 05:28 UTC, Ahmed-Abou-Emran commented
> The last issue of the context that you provided, I tried multiple times, but the issue is not happening with me. I do not know why, but I made some changes in the context, but I do not know if it will fix this issue or not. @Ahmed-Abou-Emran

I noticed that I wrote the problem because the value of the token is null, but I meant is `undefined`, to reproduce the previous issue, we need to clear the local storage first. And when we log in, the token changes in the local storage but we didn't update this change in the context.
After we refresh the page, the code in the context runs from scratch, so  `local.getItem("token")` runs a gain, but now we have a value on the local storage.

2024-03-27 05:30 UTC, Ahmed-Abou-Emran commented
Currently, everything works perfectly and the problem is fixed, since we are accessing the token inside the functions that run after we update the token in the local storage.

2024-03-27 05:31 UTC, Ahmed-Abou-Emran approved these changes

2024-03-28 15:11 UTC, merged